version: '3'
services:
  ils-app:
    container_name: ils-app
    pull_policy: build
    build: .
    stdin_open: true
    tty: true
    volumes:
      ${DIRECTORY}/code/ILS:/root/app
    ports:
      3000:3000
    labels:
      - "traefik.http.routers.ils-app.rule=Host(`ils.cheekysim.com`)"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik_default
